name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy Swagger UI and API Docs to Publish Directory
        run: |
          mkdir -p build/swagger-ui
          cp -r docs/swagger/* build/swagger-ui/
          cp docs/openapi.yaml build/swagger-ui/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/swagger-ui
          publish_branch: gh-pages
          cname: demo-local
          commit_message: ${{ github.event.head_commit.message }}
          user_name: ${{ github.event.head_commit.author.name }}
          user_email: ${{ github.event.head_commit.author.email }}
